[package]
name = "caxseii/cst-academy"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
component = "sleitnick/component@2.4.8"
goodsignal = "stravant/goodsignal@0.2.1"
topbarplus = "etheroit/topbarplus@1.0.1"
zoneplus = "mattschrubb/zoneplus@3.2.0"
timer = "sleitnick/timer@1.1.2"
input = "sleitnick/input@2.3.0"
simplepath = "untakeranonplay/simplepath@0.1.1"
janitor = "howmanysmall/janitor@1.16.0"
remotemanager = "pedro-caixa/remotemanager@0.1.1"
loader = "sleitnick/loader@2.0.0"
net = "sleitnick/net@0.2.0"
log = "sleitnick/log@0.1.1"
react = "jsdotlua/react@17.1.0"
rodux = "roblox/rodux@3.0.0"

[server-dependencies]
Cmdr = "evaera/cmdr@^1.9.0"